### ISSUE TITLE
Allow start script execution by group owner

### ISSUE THREAD

**Issue by conzetti** [paketo-buildpacks/dist-zip#175]
[Stacks](https://buildpacks.io/docs/concepts/components/stack/) that are configured to use a separate UID for the build and run operations prevent startup scripts from being executed, and likely is the culprit behind successful [buildpack participation](https://github.com/paketo-buildpacks/dist-zip#behavior). This was partially discussed in #173, but the scope was larger than that particular issue. 

Jammy-based stacks are configured to use a separate UID for build/run operations now (see [jammy-full-stack](https://github.com/paketo-buildpacks/jammy-full-stack/blob/main/stack/stack.toml#LL12C13-L12C13), so users that opt to upgrade to Jammy will have to the inability to execute startup scripts that reference other script/binary files that do not have the execute bit set.  

To workaround the current limitations, it's necessary to refactor the applications or maintain a deployment manifest that informs the deployment process how the application should run. In some cases, it ends up looking like the following:

```yaml
---
applications:
- name: foo
  path: target/foo.zip
  env:
    BP_APPLICATION_SCRIPT: foo/bin/start
    BP_LIVE_RELOAD_ENABLED: true
  process:
  - type: web
    command: >
      bash /workspace/foo/bin/setup.sh "bash somepath/foo"
```

In this example, `/workspace/foo/bin/setup.sh` is a wrapper that sets runtime variables and invokes a command via `bash -c "$@"`. To make this function, we have to prepend the string command with `bash` due to the inability to execute the command directly (lack of execute bit). 

## Describe the Enhancement
Provide the opportunity for the developer to assign  `g+x`  permissions to a path of their choosing that contains files that _should_ be executable by the run user.  This would also remove the requirement for a developer to overwrite the process that's executed, and minimize the amount of  changes required for an application to run on an updated Stack that defines separate UIDs for build/run. 

## Possible Solution
Today we're presented with `BP_APPLICATION_SCRIPT`, which provides the ability to force buildpack participation and be declarative about _what_ is being executed. A potential solution would add group execute permissions on the parent directory of the script that's defined in `BP_APPLICATION_SCRIPT`, so modern, off-the-shelf Stacks could be used if their build/run process follows a more secure pattern. 

Another solution could be an additional environment variable, for example `BP_APPLICATION_PATH_GW`, which adds recursive `g+x` permissions to a path of the developer's choosing. For example `foo/bin`. Alternatively, it could be a map that allows us to define both the the path and the mode of the directory. The downside with this approach is that the developer UX for debugging may be arguably more difficult, since it has a potential to introduce more user error. 

## Motivation
The current workarounds to adopt a Stack/ClusterStack that use separate build/run UIDs don't follow healthy patterns for application migration. A current suggestion has been to leverage a custom Stack that _does_ maintain the same UIDs for build/run, but given the direction of Stacks - it seems like we can provide a better experience to developers moving from an older stack (e.g. Bionic) or moving from Cloud Foundry _without_ requiring them to maintain a custom Stack.

**Comment by conzetti** [comment]
cc: @anthonydahanne

**Comment by dmikusa** [comment]
> Jammy-based stacks are configured to use a separate UID for build/run operations now (see [jammy-full-stack](https://github.com/paketo-buildpacks/jammy-full-stack/blob/main/stack/stack.toml#LL12C13-L12C13), so users that opt to upgrade to Jammy will have to the inability to execute startup scripts that reference other script/binary files that do not have the execute bit set.

For context, the Jammy stacks do this because of RFC https://github.com/paketo-buildpacks/rfcs/blob/main/text/0045-user-ids.md, you can see the rationale in that RFC.

The important note here is that it's the *default* behavior to use a different runtime user. You should be able to tell your container runtime to execute the image as a different user. You can do this with `docker run --user 1000:1000`, Kubernetes has similar options. I believe there are some K8s distributions that pick a random UID to run containers. Even that is OK. The buildpacks shouldn't care about the user because we either don't write to the container file system at runtime, write to `/tmp`, or we have specifically set group write permissions to the items that need to be written to.

I agree that execute for script is a bit of a different problem. The buildpacks would ensure that any scripts it knows about are set to execute correctly, like for example with Tomcat we'd make sure `catalina.sh` can run. In the case of dist-zip, it's a little trickier. In the short term, my suggestion would be to use your container runtime to change the user with your container runtime.

>Today we're presented with BP_APPLICATION_SCRIPT, which provides the ability to force buildpack participation and be declarative about what is being executed. A potential solution would add group execute permissions on the parent directory of the script that's defined in BP_APPLICATION_SCRIPT, so modern, off-the-shelf Stacks could be used if their build/run process follows a more secure pattern.

This seems reasonable. It would limit the scope of what is changed to a small set of things.

>Another solution could be an additional environment variable, for example BP_APPLICATION_PATH_GW, which adds recursive g+x permissions to a path of the developer's choosing. For example foo/bin. Alternatively, it could be a map that allows us to define both the the path and the mode of the directory. The downside with this approach is that the developer UX for debugging may be arguably more difficult, since it has a potential to introduce more user error.

@anthonydahanne and I talked about this and I'm not sure I want to introduce this into the dist-zip buildpack because setting permissions is a generic concept and I don't want to get into a situation where we have to add the same functionality to a bunch of different buildpacks. 

We also discussed the possibility of a "permissions" buildpack that lets you toggle various permissions for various paths. If we add this buildpack to the order group last, then it could run and adjust permissions as required by your application. I like that approach better. This would require an RFC & approval to add a new buildpack, but it seems generally useful so I wouldn't expect any opposition to it. It'll just take some time to go through the process.

**Comment by anthonydahanne** [comment]
Hello,
I have created an [RFC](https://github.com/paketo-buildpacks/rfcs/pull/290) for this concern since just keeping adding flags like `BP_APPLICATION_PATH_GW` or `BP_APP_PATH_GROUP_WRITABLE` to this buildpack and probably others to come is not a long term solution.

I'm sorry for thinking a flag in `dist-zip` buildpack was enough - I did not foresee that some other flags / permissions were needed and hence originally thought it was just an easy fix.

**Comment by dmikusa** [comment]
The other short term fix here would be to use an inline buildpack. https://buildpacks.io/docs/app-developer-guide/using-inline-buildpacks/

I always forget about these, but it is basically a way to run some additional commands at build time. If your build platform supports project.toml, it should allow you to use this option.

**Comment by anthonydahanne** [comment]
I gave it a try there: https://github.com/anthonydahanne/chmod-buildpack/

**Comment by anthonydahanne** [comment]
hello all!
If that's okay with you (react with a 👍 ) I'll close this issue in favor of the `chmod-buildpack`  [RFC](https://github.com/paketo-buildpacks/rfcs/pull/290) and [POC](https://github.com/anthonydahanne/chmod-buildpack/).
